#pragma once

#define EASYLOCAL_VER_MAJOR 4
#define EASYLOCAL_VER_MINOR 0
#define EASYLOCAL_VER_PATCH 0

#define EASYLOCAL_TO_VERSION(major, minor, patch) (major * 10000 + minor * 100 + patch)
#define EASYLOCAL_VERSION EASYLOCAL_TO_VERSION(EASYLOCAL_VER_MAJOR, EASYLOCAL_VER_MINOR, EASYLOCAL_VER_PATCH)