# Recall to use act --container-architecture linux/amd64 for testing the action on MacOS

name: Amalgamate Headers into a single header file with Heady

on:
    push:
        branches:
            - development
            - main
    pull_request:
        branches:
            - development
            - main

jobs:
    merge-headers:
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v2

            - name: Cache Heady Build
              uses: actions/cache@v2
              with:
                path: |
                    Heady/build
                key: ${{ runner.os }}-heady-build-${{ hashFiles('include/**/*.hpp') }}
                restore-keys: |
                    ${{ runner.os }}-heady-build-

            - name: Install dependencies (ignoring Microsoft repo)
              run: |
                sudo find /etc/apt/sources.list.d/ -type f -name '*microsoft*' -exec sudo sed -i 's/^deb/#deb/' {} \;
                sudo apt update -y 
                sudo apt install -y build-essential cmake

            - name: Install Heady
              run: |
                if [ ! -d "Heady/build" ]; then
                    git clone https://github.com/JamesBoer/Heady.git
                    cd Heady
                    mkdir build
                    cd build
                    cmake -DCMAKE_CXX_FLAGS="-Wno-error=maybe-uninitialized" ..
                    make -j       
                fi         

            - name: Run Heady to merge headers
              run: |
                Heady/build/Heady -r -s ./include -o single_include/easylocal.hpp

            - name: Commit and push if changed
              run: |
                git config --global user.email "action@github.com"
                git config --global user.name "GitHub Action"
                git add ./single_include/easylocal.hpp
                git commit -m "Update single header file" || echo "No changes to commit"
                git push origin ${GITHUB_REF##*/}
            